// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnetnodeuexpbfsyzuzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuZXRub2RldWV4cGJmc3l6dXp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMjI5MTAsImV4cCI6MjA3MTg5ODkxMH0.5FjY7TqjylAcVYv0Ot3OUTHlWCifUO5S3dXs5Wi7mo4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});